#!/usr/bin/env bash

set -xe

if ! [ -d .git ]; then
    echo "[!] Please run this script from the root of the repository"
    exit 1
fi

clang-format -i Core/Src/*.c && clang-format -i Core/Inc/*.h && clang-format -i Core/UI/**/*.c

