#!/usr/bin/env bash

# Usage: ./tools/fmt

# -------------
# Logic
# -------------

if ! [ -d .git ]; then
  echo "[!] Please run this script from the root of the repository"
  exit 1
fi

BUILD_DIR=./build
IGNORE=./Drivers
LVGL=./lvgl
STEERING=./steering/simulator

CLANG_FORMAT=clang-format

echo "[*] Formatting c files"
find . -path $BUILD_DIR -prune -false -o -path $LVGL -prune -false -o -path $IGNORE -prune -false -o -path $STEERING -prune -false -o -type f \
  -name "*.c" -exec sh -c "$CLANG_FORMAT -i \$1" _ {} \;
echo "[*] Formatting h   files"
find . -path $BUILD_DIR -prune -false -o -path $LVGL -prune -false -o  -path $IGNORE -prune -false -o -path $STEERING -prune -false -o -type f \
  -name "*.h" -exec sh -c "$CLANG_FORMAT -i \$1" _ {} \;
