[platformio]
src_dir = .
include_dir = .
default_envs = release

[env:release]
platform = ststm32
board = nucleo_h723zg
debug_tool = stlink
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
board_build.ldscript = STM32H723ZGTx_FLASH_shifted.ld

upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

extra_scripts =
    pre:scripts/build_script.py
    pre:tools/generate_fonts.py
build_flags =
    -std=gnu23
    -DUSE_HAL_DRIVER
    -DSTM32H723xx
    -D_XOPEN_SOURCE
    -ICore/Inc
    -ICore/Inc/steering
    -ICore/Inc/steering/drivers
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc
    -isystem Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
    -isystem Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -isystem Drivers/CMSIS/Include
    -Itools/generated
build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32H7xx_HAL_Driver/Src>
    -<Drivers/STM32H7xx_HAL_Driver/Src/*_template.c>
    +<startup_stm32h723xx.s>
    +<tools/generated/*.c>
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw.git#v0.1.0
    https://github.com/eagletrt/libpal-sw.git#v0.1.0
    https://github.com/eagletrt/libraster-sw.git#v2.1.0
    https://github.com/eagletrt/libcan-sw.git

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
    clangtidy: --extra-arg=-std=gnu23
    clangtidy: --extra-arg=-U__cplusplus
check_src_filters =
    -<**>
    +<Core/Src/steering>
    +<Core/Inc/steering>
