#ifndef STEERING_CONFIG_H
#define STEERING_CONFIG_H

#define SDRAM_BASE_ADDRESS 0xC0000000
#define FRAMEBUFFER1_ADDR SDRAM_BASE_ADDRESS
#define FRAMEBUFFER2_ADDR 0xC0200000

#if CANSNIFFER_ENABLED == 1
#define PRIMARY_CANSNIFFER_MEMORY_POOL_ADDRESS 0xC0600000
#define SECONDARY_CANSNIFFER_MEMORY_POOL_ADDRESS                               \
  ((0xC0600000) + ((CANSNIFFER_ELEM_T_SIZE) * CAN_POSSIBLE_IDS))
#endif

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480

uint32_t get_current_time_ms(void);

#endif // STEERING_CONFIG_H
