/******************************************************************************
Finite State Machine
Project: steering_wheel_fsm
Description: Steering Wheel FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2025-12-20 21:29:23 +0100
Generated from: fsm.dot
The finite state machine has:
  7 states
  11 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>
#include <stdbool.h>

/*** USER CODE BEGIN MACROS ***/
#include "leds.h"

/*** USER CODE END MACROS ***/

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
/*** USER STATE DATA TYPE BEGIN ***/
typedef void fsm_state_data_t;
/*** USER STATE DATA TYPE END ***/
// Event data object
// By default the struct is empty; put the data of the event inside
// the structure if you need or leave it empty
typedef struct {

    /*** USER CODE BEGIN EVENT_DATA ***/

    void *empty_for_warning;

    /*** USER CODE END EVENT_DATA ***/

} fsm_event_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    FSM_STATE_INIT = 0,
    FSM_STATE_IDLE,
    FSM_STATE_ERROR,
    FSM_STATE_FLASH,
    FSM_STATE_TS_ON,
    FSM_STATE_AUTONOMOUS,
    FSM_STATE_DRIVE,
    FSM_NUM_STATES,
    FSM_NO_CHANGE
} fsm_state_t;

// State human-readable names
extern const char *fsm_state_names[];

// State function and state transition prototypes
typedef fsm_state_t fsm_state_func_t(fsm_state_data_t *data);
typedef void transition_func_t(fsm_state_data_t *data);

/*** USER CODE BEGIN TYPES ***/

/*!
 * \brief This struct contains the data needed by the FSM to operate and call other modules successfully. It is passed as an argument to all state and transition functions.
 */
struct FsmData {
    uint32_t tick; /*!< Current tick. */
};

/*** USER CODE END TYPES ***/

// Functions to check and trigger an event
bool fsm_is_event_triggered();
void fsm_event_trigger(fsm_event_data_t *event);

// State functions

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data);

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR, FSM_STATE_TS_ON, FSM_STATE_AUTONOMOUS
fsm_state_t fsm_do_idle(fsm_state_data_t *data);

// Function to be executed in state error
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_error(fsm_state_data_t *data);

// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_flash(fsm_state_data_t *data);

// Function to be executed in state ts_on
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR, FSM_STATE_DRIVE
fsm_state_t fsm_do_ts_on(fsm_state_data_t *data);

// Function to be executed in state autonomous
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_autonomous(fsm_state_data_t *data);

// Function to be executed in state drive
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_drive(fsm_state_data_t *data);

// List of state functions
extern fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES];

// Transition functions
void fsm_init_done(fsm_state_data_t *data);
void fsm_init_error(fsm_state_data_t *data);
void fsm_start_flash(fsm_state_data_t *data);
void fsm_error_detected(fsm_state_data_t *data);
void fsm_ts_on_request(fsm_state_data_t *data);
void fsm_autonomous_enable(fsm_state_data_t *data);
void fsm_flash_done(fsm_state_data_t *data);
void fsm_ts_cancel(fsm_state_data_t *data);
void fsm_ts_on_accepted(fsm_state_data_t *data);
void fsm_ts_off(fsm_state_data_t *data);
void fsm_autonomous_disable(fsm_state_data_t *data);

// Table of transition functions
extern transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES];

// state manager
fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data);

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#endif
