all:
	gcc -I../../Lib/micro-libs/min-heap/inc -I../steering -I../../Lib/can/lib/primary max_heap_tests.c ../steering/maxheap.c ../../Lib/can/lib/primary/primary_network.c ../../Lib/micro-libs/min-heap/src/min-heap.c -o max_heap_tests


