/******************************************************************************
Finite State Machine
Project: steering_wheel_fsm
Description: Steering Wheel FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-07-27 09:05:05 +0200
Generated from: fsm.dot
The finite state machine has:
  5 states
  7 transition functions
Functions and types have been generated with prefix "fsm_"
******************************************************************************/

#include "fsm.h"

/*** USER CODE BEGIN MACROS ***/

#include "can-communications-api.h"
#include "inputs-api.h"
#include "post-api.h"
#include "screen-api.h"
#include "ui-data-api.h"
#include "eagletrt-api.h"
#include "can-communications-router-api.h"

/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *fsm_state_names[] = { "init", "idle", "error", "flash", "autonomous" };

// List of state functions
fsm_state_func_t *const fsm_state_table[FSM_NUM_STATES] = {
    fsm_do_init,       // in state init
    fsm_do_idle,       // in state idle
    fsm_do_error,      // in state error
    fsm_do_flash,      // in state flash
    fsm_do_autonomous, // in state autonomous
};

// Table of transition functions
transition_func_t *const fsm_transition_table[FSM_NUM_STATES][FSM_NUM_STATES] = {
    /* states:        init                  , idle                  , error                 , flash                 , autonomous             */
    /* init       */ { NULL, fsm_init_done, fsm_init_error, NULL, NULL },
    /* idle       */ { NULL, NULL, fsm_error_detected, fsm_start_flash, fsm_autonomous_enable },
    /* error      */ { NULL, NULL, NULL, NULL, NULL },
    /* flash      */ { NULL, fsm_flash_done, fsm_error_detected, NULL, NULL },
    /* autonomous */ { NULL, fsm_autonomous_disable, fsm_error_detected, NULL, NULL },
};

// Triggered event
fsm_event_data_t *fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/

/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool fsm_is_event_triggered() {
    return fsm_fired_event != NULL;
}

// Function to trigger an event
void fsm_event_trigger(fsm_event_data_t *event) {
    if (fsm_fired_event != NULL) {
        return;
    }
    fsm_fired_event = event ? event : &(fsm_event_data_t){ .empty_for_warning = NULL };
}

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_init(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_INIT ***/

    struct PostInitData *post_init_data = (struct PostInitData *)data;

    if (post_api_do_init(post_init_data) != POST_RC_OK) {
        next_state = FSM_STATE_ERROR;
    }

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR, FSM_STATE_AUTONOMOUS
fsm_state_t fsm_do_idle(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_IDLE ***/

    if (data == NULL) {
        next_state = FSM_STATE_ERROR;
    } else {
        struct FsmData *fsm_data = (struct FsmData *)data;

        if (can_communications_router_api_reset_asked()) {
            fsm_data->reset();
        }

        // A transient NAK from the input expanders is not worth bricking
        // the wheel over: FSM_STATE_ERROR has no way back, so treating it
        // as fatal would freeze the dashboard for the rest of the power
        // cycle. The display is the one thing the driver actually needs.
        EAGLETRT_API_UNUSED(inputs_api_poll_for_long_press(fsm_data->tick));

        // TODO: add check for return values, and handle errors accordingly
        EAGLETRT_API_UNUSED(can_communications_api_process_rx(CAN_COMMUNICATION_NETWORK_PRIMARY));
        EAGLETRT_API_UNUSED(can_communications_api_process_rx(CAN_COMMUNICATION_NETWORK_SECONDARY));

        EAGLETRT_API_UNUSED(can_communications_api_process_tx(CAN_COMMUNICATION_NETWORK_PRIMARY));
        EAGLETRT_API_UNUSED(can_communications_api_process_tx(CAN_COMMUNICATION_NETWORK_SECONDARY));

        // Pull the latest telemetry snapshot into the dashboard before the
        // raster runs; setters are no-ops when nothing changed, so this is
        // cheap to call every tick.
        if (screen_api_sync_data(ui_data_api_get()) != SCREEN_RC_OK) {
            next_state = FSM_STATE_ERROR;
        }

        switch (screen_api_update(fsm_data->tick)) {
            case SCREEN_RC_OK:
                break;
            case SCREEN_RC_RENDERED: {
                if (fsm_data->swap_framebuffers == NULL) {
                    next_state = FSM_STATE_ERROR;
                    break;
                }
                fsm_data->swap_framebuffers();
                break;
            }

            case SCREEN_RC_ERROR:
            case SCREEN_RC_NULL_POINTER:
                next_state = FSM_STATE_ERROR;
        }
    }

    /*** USER CODE END DO_IDLE ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
        case FSM_STATE_AUTONOMOUS:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state error
// valid return states: FSM_NO_CHANGE, FSM_STATE_ERROR
fsm_state_t fsm_do_error(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_ERROR ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END DO_ERROR ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: FSM_NO_CHANGE, FSM_STATE_IDLE, FSM_STATE_FLASH, FSM_STATE_ERROR
fsm_state_t fsm_do_flash(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_NO_CHANGE;

    /*** USER CODE BEGIN DO_FLASH ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END DO_FLASH ***/

    switch (next_state) {
        case FSM_NO_CHANGE:
        case FSM_STATE_IDLE:
        case FSM_STATE_FLASH:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state autonomous
// valid return states: FSM_STATE_IDLE, FSM_STATE_ERROR
fsm_state_t fsm_do_autonomous(fsm_state_data_t *data) {
    fsm_state_t next_state = FSM_STATE_IDLE;

    /*** USER CODE BEGIN DO_AUTONOMOUS ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END DO_AUTONOMOUS ***/

    switch (next_state) {
        case FSM_STATE_IDLE:
        case FSM_STATE_ERROR:
            break;
        default:
            next_state = FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | |
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void fsm_init_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_DONE ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END INIT_DONE ***/
}

// This function is called in 1 transition:
// 1. from init to error
void fsm_init_error(fsm_state_data_t *data) {

    /*** USER CODE BEGIN INIT_ERROR ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END INIT_ERROR ***/
}

// This function is called in 1 transition:
// 1. from idle to flash
void fsm_start_flash(fsm_state_data_t *data) {

    /*** USER CODE BEGIN START_FLASH ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END START_FLASH ***/
}

// This function is called in 3 transitions:
// 1. from idle to error
// 2. from flash to error
// 3. from autonomous to error
void fsm_error_detected(fsm_state_data_t *data) {

    /*** USER CODE BEGIN ERROR_DETECTED ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END ERROR_DETECTED ***/
}

// This function is called in 1 transition:
// 1. from idle to autonomous
void fsm_autonomous_enable(fsm_state_data_t *data) {

    /*** USER CODE BEGIN AUTONOMOUS_ENABLE ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END AUTONOMOUS_ENABLE ***/
}

// This function is called in 1 transition:
// 1. from flash to idle
void fsm_flash_done(fsm_state_data_t *data) {

    /*** USER CODE BEGIN FLASH_DONE ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END FLASH_DONE ***/
}

// This function is called in 1 transition:
// 1. from autonomous to idle
void fsm_autonomous_disable(fsm_state_data_t *data) {

    /*** USER CODE BEGIN AUTONOMOUS_DISABLE ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END AUTONOMOUS_DISABLE ***/
}

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|
 *                              |___/
 */

fsm_state_t fsm_run_state(fsm_state_t cur_state, fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    fsm_event_data_t *prev_ev = fsm_fired_event;
    fsm_state_t new_state = fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL) {
        fsm_fired_event = NULL;
    }
    if (new_state == FSM_NO_CHANGE) {
        new_state = cur_state;
    }
    transition_func_t *transition = fsm_transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }
    return new_state;
}

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    fsm_state_t cur_state = FSM_STATE_INIT;
    do {
        cur_state = fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
